all_atoms: false
atom_max_neighbors: 8
atom_radius: 5
atom_type_prediction: true
batch_size: 16
bond_type_prediction: true
c_alpha_max_neighbors: 24
cache_path: ~/cache_RTMScoreFeature_Surface_PDBBIND_pocket_8A_randomsplit_rtmscore_valset_1
config: null
cross_distance_embed_dim: 32
cross_max_distance: 80
cudnn_benchmark: true
data_dir: ~/PDBBind_pocket_8A/
distance_embed_dim: 32
dropout: 0.1
dynamic_max_cross: true
ema_rate: 0.999
embedding_scale: 1000
embedding_type: sinusoidal
esm_embeddings_path: ~/esm_embedding/esm_embedding_pocket_for_train/esm2_3billion_embeddings.pt
inference_earlystop_goal: max
inference_earlystop_metric: valinf_rmsds_lt2
inference_steps: 20
ligand_distance_prediction: false
limit_complexes: 0
log_dir: ~_rtmscore_split/workdir
lr: 0.001
matching: true
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_radius: 5.0
mdn_dist_threshold_test: 5.0
mdn_dist_threshold_train: 7.0
mdn_dropout: 0.1
mdn_early_stop_patience: 30
model_type: mdn_model
model_version: version6
n_epochs: 850
n_gaussians: 20
no_batch_norm: false
no_torsion: true
ns: 40
num_conformers: 1
num_conv_layers: 4
num_dataloader_workers: 1
num_inference_complexes: 500
num_workers: 1
nv: 10
pin_memory: false
project: mdn_diffScreen_pocket_8A_V6_surface_rtmscore_split
receptor_radius: 15.0
remove_hs: true
residue_type_prediction: false
restart_dir: null
restart_lr: null
rot_sigma_max: 1.0e-21
rot_sigma_min: 1.0e-18
rot_weight: 0.33
run_name: project_mdn_diffScreen_pocket_8A_V6_surface_rtmscore_split_valset_1_RunTime_2023_11_06_07_12_49_ns_40_nv_10_layer_4_lr_1e-3_gussions_20_train_dist_7_test_dist_5_bs_16_use_orig_pos_mdn_inter_loss_atom_type_loss_bond_type_loss2023-11-06_07-13-27
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 30
sigma_embed_dim: 32
split_test: ~/data/splits/timesplit_test
split_train: ~/data/splits/timesplit_no_lig_overlap_train
split_val: ~/data/splits/timesplit_no_lig_overlap_val
surface_path: null
test_sigma_intervals: true
topN: 1
tor_sigma_max: 1.0e-23
tor_sigma_min: 1.0e-21
tor_weight: 0.33
tr_sigma_max: 1.0e-20
tr_sigma_min: 1.0e-18
tr_weight: 0.33
train_inference_freq: null
transformStyle: diffdock
use_ema: false
use_second_order_repr: false
val_inference_freq: 5
w_decay: 0.0
wandb: true
wandb_dir: ~_rtmscore_split
